# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Boiler add-on
version: "0.0.1.1"
slug: smart-boiler
description: Smart Boiler add-on
url: "https://github.com/grinwi/smart_boiler_hassio_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
#image: "grinwi/image-{arch}-smart_boiler"
map:
  - share:rw
#image: "ghcr.io/home-assistant/{arch}-addon-example"
# devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
