# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Boiler add-on
version: "0.0.1.4"
slug: smartboiler
description: Smart Boiler add-on
url: "https://github.com/grinwi/smart_boiler_hassio_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "grinwi/image-{arch}-smartboiler"
map:
  - config:rw
  - share:rw
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface and API
webui: http://[HOST]:[PORT:5000]
init: false
hassio_role: default
homeassistant_api: true
ingress: true
ingress_port: 5000
ingress_stream: true
